server:
  port: "8080"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"
  shutdown_timeout: "30s"

database:
  host: "localhost"
  port: 5432
  user: "urlshortener"
  password: "password"
  dbname: "urlshortener"
  sslmode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "5m"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5
  max_retries: 3
  ttl: "24h"
  negative_ttl: "5m"

rate_limit:
  global_rps: 100
  per_ip_rps: 10
  burst_size: 20
  window_size: "1s"

security:
  admin_secret: "your-secret-key-here"
  allowed_origins:
    - "http://localhost:3000"
    - "https://yourdomain.com"
  allowed_hosts:
    - "www.google.com"
    - "google.com"
    - "example.com"
    - "github.com"
    - "stackoverflow.com"
    - "localhost"
  blocked_domains:
    - "malicious-site.com"
    - "spam-domain.org"

logging:
  level: "info"
  format: "json"
